### ISSUE TITLE
Enhancement SystemTokenManager pallet

### ISSUE THREAD

**Issue by sweatpotato13** [InfraBlockchain/infra-relay-chain#40]
### Request

* `SystemTokenExchangeRate` -> change name
* `SysytemTokenMetadata` -> add epoch time
* `SystemTokenOnParachain` -> add epoch time
* `SystemTokenByParaId` -> Reverse storage of `SystemTokenOnParachainByParaId`
* `registerSystemToken` -> Weight로 변경

**Comment by energyGiver** [comment]
@sweatpotato13  As the issue we saw last friday, when called `register_system_token`, it would be great to add a logic to store the system_token_id pair to SystemTokenOnParachain like below! Thanks. 

SystemTokenOnParachain::<T>::insert(&system_token_id, &system_token_id);
